changelog:
  categories:
    - title: ⚠️ Breaking Changes ⚠️
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Maintenance
      labels:
        - chore
        - documentation
        - testing
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
