version: "2"
linters:
  enable:
    - godot
    - misspell
    - revive
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
    revive:
      rules:
        - name: unchecked-type-assertion
          arguments:
            - acceptIgnoredAssertionResult: true
        - name: early-return
        - name: redundant-import-alias
        - name: redefines-builtin-id
        - name: struct-tag
        - name: receiver-naming
        - name: deep-exit
        - name: bool-literal-in-expr
        - name: comment-spacings
        - name: confusing-results
        - name: use-any
        - name: bare-return
        - name: empty-block
        - name: range-val-address
        - name: range-val-in-closure
        - name: var-declaration
        - name: useless-break
        - name: error-naming
        - name: indent-error-flow
        - name: datarace
        - name: modifies-value-receiver
        - name: empty-lines
        - name: duplicated-imports
        - name: error-return
    staticcheck:
      checks:
        - all
        - -ST1000 # Package comment should be of the form "Package provider...".
        - -ST1003 # Should not use underscores in Go names.
        - -ST1005 # Error strings should not be capitalized or end with a new line.
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
