name: LXD Cluster Setup
description: Sets up the LXD cluster for testing.

inputs:
  cluster-name:
    description: |
      The name of the cluster. Used as a prefix for cluster member
      instances and as a name of the remote on a local LXD client.
    default: cls
  cluster-size:
    description: The size of the cluster.
    default: 3
  instance-type:
    description: The instance type of the cluster member.
    default: 'container'
    options:
      - container
      - virtual-machine
  lxd-version:
    description: The version of LXD to install on each cluster member.
    default: latest/edge

runs:
  using: composite
  steps:
    - name: Reclaim disk space
      uses: canonical/lxd/.github/actions/reclaim-disk-space@main

      # Remove Docker to avoid conflicts with LXD networks.
    - name: Remove Docker
      uses: canonical/lxd/.github/actions/disable-docker@main

    - name: Remove existing snaps
      shell: bash
      run: |
        for s in $(snap list | awk '!/^(Name|core|snapd)/ {print $1}'); do
          sudo snap remove --purge "${s}" || true
        done

    - name: Setup LXD
      shell: bash
      run: |
        sudo snap install lxd --channel=latest/stable
        sudo lxd waitready --timeout 60
        sudo lxd init --auto --network-port=8443 --network-address=localhost
        sudo chmod 777 /var/snap/lxd/common/lxd/unix.socket

    - run: ./lxd-cluster.sh deploy
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        CLUSTER_SIZE: ${{ inputs.cluster-size }}
        INSTANCE_TYPE: ${{ inputs.instance-type }}
        INSTANCE_IMAGE: ubuntu:24.04
        VERSION_LXD: ${{ inputs.lxd-version }}
